owner: adlaidyson-ffp
repo: statusadffp

sites:
  - name: Main Website
    url: https://www.fusedframe.co.uk
  - name: Link in Bio
    url: https://links.adlaidyson.co.uk
  - name: Client Galleries (PICR)
    url: https://clients.adlaidyson.co.uk
  - name: ADFFP Cloud (NextCloud)
    url: https://cloud.fusedframe.co.uk
  - name: DocuSign (Document Signing Platform)
    url: https://sign.adlaidyson.co.uk
  - name: Content Delivery Network (CDN) - Cloudflare R2
    url: https://cdn-eu.fusedframe.co.uk/main-branding/status.html
  - name: URL Shortner - adffp.uk
    url: adffp.uk
  - name: Shutter Society Mastodon
    url: shuttersociety.uk
  - name: Upper Haugh Weather (Frontend)
    url: upperhaughweather.uk
  - name: Upper Haugh Weather (API Backend)
    url: api.upperhaughweather.uk/weather

status-website:
  cname: status.adffp.uk
  logoUrl: https://cdn-eu.fusedframe.co.uk/main-logos/jpg/squarefavicon-nocircle.jpg
  name: Service Statuses
  introTitle: "**Service Statuses**"
  introMessage: View the status for all services used or hosted by Adlai Dyson | Fused Frame Photography.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://www.fusedframe.co.uk
    - title: All Links
      href: https://links.adlaidyson.co.uk
